### PR TITLE
differentiating test assemblies names

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to https://github.com/RadicalFx/housekeeping/issues/55

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny quick and dirty fix to allow tests in multiple tests projects with the same name to work with AppVeyor, please review and merge

**Comment by micdenny** [comment]
now seems to be ok:
image
:smile:

**Comment by massimopasquali** [comment]
Hi, I'm starting to use radical in a universal up. Have same example and documentation more specify for Radical universal app?

**Comment by massimopasquali** [comment]
Hi, I'm starting to use radical in a universal up. Have same example and documentation more specify for Radical universal app?

**Comment by massimopasquali** [comment]
Hello,
I'm developing an Universal App using Radical, so this afternoon I have tried to use this Namespace in my XMAL

xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:markup="http://schemas.topics.it/wpf/radical/windows/markup"
xmlns:behavior="http://schemas.topics.it/wpf/radical/windows/behaviors"

But I haven't been able to do that Text="{markup:EditorBinding TargetSpeed}"

can you help me, give me some suggestions?

grazie

**Comment by mauroservienti** [comment]
Hi @massimopasquali, sorry for the delay busy days. Can you please raise an issue in the UWP repo here: https://github.com/RadicalFx/radical-universal/issues ?

Cheers,
.m

**Comment by mauroservienti** [comment]
@massimopasquali 

> Hi, I'm starting to use radical in a universal up. Have same example and documentation more specify for Radical universal app?

Documentation not yet, we have docu for the full fx, WPF, here https://github.com/RadicalFx/Radical/wiki
UWP is yet to be ready, we have a plan but not enough resources at the moment

**Pull request merged**
