### PR TITLE
Update GitVersionConfig.yaml

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to https://github.com/RadicalFx/housekeeping/issues/50

### CODE REVIEW

**Comment by micdenny** [comment]
don't know why the build failed, trying forcing a re-build of the PR

**Comment by micdenny** [comment]
Now the build error points out to git version, it can't connect to somewhere:

```
MSBUILD : error : Error occurred: System.Net.WebException: The remote server returned an error: (500) Internal Server Error. [C:\projects\radical\src\net35\Radical\Radical.csproj]
MSBUILD : error :    at System.Net.HttpWebRequest.GetResponse() [C:\projects\radical\src\net35\Radical\Radical.csproj]
MSBUILD : error :    at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables) [C:\projects\radical\src\net35\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.WriteIntegrationParameters(IEnumerable`1 applicableBuildServers, VersionVariables variables) [C:\projects\radical\src\net35\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.InnerExecute() [C:\projects\radical\src\net35\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.Execute() [C:\projects\radical\src\net35\Radical\Radical.csproj]
MSBUILD : error : Error occurred: System.Net.WebException: The remote server returned an error: (500) Internal Server Error. [C:\projects\radical\src\net40\Radical\Radical.csproj]
MSBUILD : error :    at System.Net.HttpWebRequest.GetResponse() [C:\projects\radical\src\net40\Radical\Radical.csproj]
MSBUILD : error :    at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables) [C:\projects\radical\src\net40\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.WriteIntegrationParameters(IEnumerable`1 applicableBuildServers, VersionVariables variables) [C:\projects\radical\src\net40\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.InnerExecute() [C:\projects\radical\src\net40\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.Execute() [C:\projects\radical\src\net40\Radical\Radical.csproj]
MSBUILD : error : Error occurred: System.Net.WebException: The remote server returned an error: (500) Internal Server Error. [C:\projects\radical\src\net45\Radical\Radical.csproj]
MSBUILD : error :    at System.Net.HttpWebRequest.GetResponse() [C:\projects\radical\src\net45\Radical\Radical.csproj]
MSBUILD : error :    at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables) [C:\projects\radical\src\net45\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.WriteIntegrationParameters(IEnumerable`1 applicableBuildServers, VersionVariables variables) [C:\projects\radical\src\net45\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.InnerExecute() [C:\projects\radical\src\net45\Radical\Radical.csproj]
MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.Execute() [C:\projects\radical\src\net45\Radical\Radical.csproj]
```

**Comment by micdenny** [comment]
probably something related to the communication to appveyor `GitVersion.AppVeyor.GenerateSetVersionMessage` <-> `GetResponse`

**Comment by mauroservienti** [comment]
I noticed that, I'll have a look at it tomorrow morning. I was building previously, so should be a connectivity issue. We'll see.

**Comment by mauroservienti** [comment]
I don't know, seems to be a commit that is causing the issue, I just merged https://github.com/RadicalFx/Radical/pull/220 and the build worked as expected. Should we try to merge this one and see what happens? Otherwise I can ping the `GitVersion` people and ask if they can have a look.

**Comment by micdenny** [comment]
What about enabling high detailed log of appveyor and most important on gitversion if it has the option to do so

**Comment by mauroservienti** [comment]
good point, I'll do.

**Comment by mauroservienti** [comment]
build is now green, I've set it back to `minimal` verbosity, let's see.

**Comment by micdenny** [comment]
ok now is building, so it was a temporary problem, strange anyway, I'm curious to know what it was, btw I can merge now.

do you want to remove the useless commit? do you know that now we can use the [`squash` git feature also in github](https://github.com/blog/2141-squash-your-commits), to have a clean master history avoiding this kind of small/test commit, and push with a concise feature description.

**Comment by mauroservienti** [comment]
yeah, squashed + force push. Building again, if green I'll merge.

**Comment by micdenny** [comment]
great!

**Pull request merged**
