### PR TITLE
Release/1.6.0

### PR DESCRIPTION
**Pull request by mauroservienti**
@micdenny the goal of this release is primarily to bring the new CI process to master. Shall we go?

### CODE REVIEW

**Comment by micdenny** [comment]
testing alpha package

**Comment by micdenny** [comment]
works like a charm, merging

**Comment by micdenny** [comment]
boom :bomb: let's see!!

**Comment by micdenny** [comment]
image

amazing, it just works!

**Comment by mauroservienti** [comment]
yeah! and release as well:

image

**Comment by micdenny** [comment]
cool!

**Comment by mauroservienti** [comment]
there is only one thing, and I think we should raise a separate issue. If you take a look at the [build logs](https://ci.appveyor.com/project/radical-bot/radical) it seems that the build process discovered and executed only 2 tests. Strange indeed.

**Comment by mauroservienti** [comment]
We might need to add something like:

```
  assemblies:
    - '**\*.tests.dll
```

to the `tests` section

**Comment by mauroservienti** [comment]
In case of the `Radical` project the search pattern should be `'**\Test*.dll`

**Comment by mauroservienti** [comment]
Anyway this is done!

**Comment by micdenny** [comment]
yes, open a separated issue for that, it's easy then to fix it, it is something for `develop` branch

**Pull request merged**
