### PR TITLE
Puzzle forwarding support

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny please review

**Comment by micdenny** [comment]
@mauroservienti why not adding also the `Forward` method on the non-generic [`IPuzzleContainerEntry`](https://github.com/RadicalFx/Radical/blob/puzzle-forwarding-support/src/net35/Radical/ComponentModel/Container/IPuzzleContainerEntry.cs) class?

**Comment by mauroservienti** [comment]
Let...me...think...to a good reason...I'll find one, I swear :-)

Good point I'll raise an issue.

**Comment by mauroservienti** [comment]
@micdenny done.

**Comment by micdenny** [comment]
that's what i meant ;)

**Pull request merged**
