### PR TITLE
Move to gitversion

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to https://github.com/RadicalFx/housekeeping/issues/35

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny this is ready for review, the goal is to [move to GitVersion](https://github.com/RadicalFx/housekeeping/issues/35) to better handle automatic versioning, especially for contributors so to avoid asking everyone to manually bump the version when opening a PR.

Please review

**Comment by micdenny** [comment]
Great, I'll review probably this weekend

**Comment by mauroservienti** [comment]
squashed and force pushed

**Comment by mauroservienti** [comment]
@micdenny ping :smile:

**Comment by mauroservienti** [comment]
Since we verified on `Radical.Windows.Presentation.CastleWindsor` that the process works, if no objections are made I'll merge this one in a couple of hours.

**Pull request merged**
