### PR TITLE
Release 1.5.3

### PR DESCRIPTION
**Pull request by mauroservienti**
Releasing to production 1.5.3, the #195 fix has been tested by the user confirming that the issue is resolved.
@micdenny, now should be fine. Up to you to release to NuGet for the first time :-)

### CODE REVIEW

**Comment by micdenny** [comment]
can you add this configuration to `appveyor.yml` just like [here](https://github.com/RadicalFx/Radical.Windows.Presentation/blob/develop/appveyor.yml):

```
  pull_requests:
    do_not_increment_build_number: true
```

I think I will need to add this configuration in many other repo, but we can do as soon as we have to push something new, it is not urgent.

**Comment by mauroservienti** [comment]
Done, please review, should I open an issue in housekeeping to track this?

**Comment by micdenny** [comment]
> should I open an issue in housekeeping to track this?

no, that's ok, actually it is not mandatory, just fancy :smile:

**Comment by micdenny** [comment]
let's do this.... :pray:

**Comment by mauroservienti** [comment]
it's live on NuGet, yeah :-)

**Comment by micdenny** [comment]
package went on nuget.org as expected:

image

Great!! :smile:

**Comment by mauroservienti** [comment]
BTW I did everything from the GitHub web interface to release, easy peasy :smile:

**Comment by micdenny** [comment]
cool, which steps did you do?

**Comment by mauroservienti** [comment]
I did nothing :-)

**Pull request merged**
