### PR TITLE
Makes the Puzzle SubscribeToMessage facility compatible with legacy broker messages implementing the IMessage interface.

### PR DESCRIPTION
**Pull request by mauroservienti**
@micdenny please review.

### CODE REVIEW

**Comment by micdenny** [comment]
tested and works, merging!

```c#
using System;
using Topics.Radical;
using Topics.Radical.ComponentModel.Messaging;
using Topics.Radical.Messaging;
using Topics.Radical.Threading;

namespace ConsoleApplication1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var sender = new object();

            {
                var container = new PuzzleContainer();
                container.AddFacility<SubscribeToMessageFacility>();
                container.Register(EntryBuilder.For<IMessageBroker>().UsingInstance(new MessageBroker(new NullDispatcher())));
                container.Register(EntryBuilder.For<IMessageHandler<LegacyMessage>>().ImplementedBy<LegacyMessageHandler>());

                var broker = container.Resolve<IMessageBroker>();

                broker.Dispatch(new LegacyMessage(sender)
                {
                    Content = "I am so legacy, sorry!"
                });
            }

            {
                var container = new PuzzleContainer();
                container.AddFacility<SubscribeToMessageFacility>();
                container.Register(EntryBuilder.For<IMessageBroker>().UsingInstance(new MessageBroker(new NullDispatcher())));
                container.Register(EntryBuilder.For<IHandleMessage<MyMessage>>().ImplementedBy<MyMessageHandler>());

                var broker = container.Resolve<IMessageBroker>();

                broker.Dispatch(sender, new MyMessage
                {
                    Content = "What a fresh message man!!"
                });
            }
        }
    }

    public class LegacyMessage : Message
    {
        public LegacyMessage(object sender)
            : base(sender)
        {
        }

        public string Content { get; set; }
    }
    
    public class LegacyMessageHandler : MessageHandler<LegacyMessage>
    {
        public override void Handle(LegacyMessage message)
        {
            Console.WriteLine($"Legacy message handled: {message.Content}");
        }
    }

    public class MyMessage
    {
        public string Content { get; set; }
    }

    public class MyMessageHandler : AbstractMessageHandler<MyMessage>
    {
        public override void Handle(object sender, MyMessage message)
        {
            Console.WriteLine($"My message handled: {message.Content}");
        }
    }
}
```

**Comment by micdenny** [comment]
@mauroservienti can you please bump the version?

**Comment by mauroservienti** [comment]
Done

**Comment by mauroservienti** [comment]
@micdenny any option you can have at this and merge? cheers.

**Comment by micdenny** [comment]
no nothing, I was just sleeping :smile:

**Comment by mauroservienti** [comment]
thanks :)

**Pull request merged**
