### PR TITLE
prep move to NET Standard 2

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to #258 

- [x] Upgraded to new project format 
- [x] Removed all versions and add support for .NET 4.6 and netstandard2.0
- [x] Command line build support via BullsEye
- [x] Simplified AppVeyor configuration 
- [x] Removed `Topics` from namespaces and artifacts names
- ~move to .NET 4.7.2 only in light of supporting NET Standard 2~ Not needed to just go straight to NET Standard 2

### CODE REVIEW

**Comment by micdenny** [comment]
Why support only 4.7? There are new framework features you would like to use in radical? Something related to performance that we can take advantage only if we compile against 4.7?

**Comment by mauroservienti** [comment]
7ff08109-ef3b-4e68-ad9b-1ca83678ca64

**Comment by micdenny** [comment]
Probably that’s fine to go only with one target, old fx will stick to old radical version like we will do for some time

**Comment by mauroservienti** [comment]
@micdenny @nazarenomanco removed the WIP as this is ready to go, it's the first step in order to support `netstandard2.0`.

Please note that I also switched from GitVersion to MinVer:
- it's much simpler than GitVersion
- a GitVersion dependency is causing troubles hen using `dotnet build` to compile the solution

Please review. I know that it's a complex one, there are a lot of deletion 🎉 and you should be able to review commit b commit. I like to get this going, as supporting `netstandard2.0` opens up to move downstreams to `NET Core 3.0`.

**Pull request merged**
