### PR TITLE
Dispose singleton instances at container disposal

### LINKED ISSUE #145: PuzzleContainer: disposition of singleton instances at container disposal
Misses:

    this.trackedSingletons.Values
        .OfType<IDisposable>()
        .ToList()
        .ForEach( d => d.Dispose() );

and components Release support

--

related to #134

### PR DESCRIPTION
**Pull request by mauroservienti**
fix #145, @micdenny please review.

### CODE REVIEW

**Comment by micdenny** [comment]
great, thanks!

**Comment by micdenny** [comment]
@mauroservienti bump the version, so I can merge it

**Comment by micdenny** [comment]
@mauroservienti you will have to rebase, because I've merged #207

**Comment by mauroservienti** [comment]
@micdenny rebased and bumped.

**Comment by micdenny** [comment]
thank you!

**Pull request merged**
