### PR TITLE
blend sdk binaries restored from nuget

### PR DESCRIPTION
**Pull request by micdenny**
@mauroservienti Is that ok for you?

### CODE REVIEW

**Comment by mauroservienti** [comment]
to me it is good, have you tested that the WPF designer still works when creating a new project using the Interactivity nuget package? I remember I had some issues, at least with VS2013. Can you test it?

**Comment by micdenny** [comment]
Step to reproduce:

- [ ] Create new blank WPF project
- [ ] Add [Expression.Blend.Sdk](https://www.nuget.org/packages/Expression.Blend.Sdk/)
- [ ] In the window use a behavior from interactivity

@mauroservienti Is that correct?

**Comment by mauroservienti** [comment]
If I recall correctly yes

**Comment by micdenny** [comment]
ok I check and tell you the results

**Comment by micdenny** [comment]
I've tried on a blank project and it works.
I've tried on the Radical.Samples and every behaviors works.

The designer in both projects works, actually I don't see any error, and all the controls are rendered.

@mauroservienti Could I proceed and merge it?

**Comment by mauroservienti** [comment]
Go :-)

Sent from my Amazing not anymore Yellow Lumia, typos are guaranteed ;-)
________________________________

**Comment by mauroservienti** [comment]
great, does this mean that we can update the readme.md and the readme files in the NuGet packages removing the dependency on the Blend SDK?

@enosrecanati could you check if the same SDK should be removed from the Universal App support?

**Comment by micdenny** [comment]
> great, does this mean that we can update the readme.md and the readme files in the NuGet packages removing the dependency on the Blend SDK?

yes I think we don't need to specify those requirements, because now it's all managed by nuget package restore. We can leave the note on NuBuild extension, even if will be removed when CI #93  process will be ready :smile:

**Comment by micdenny** [comment]
> @enosrecanati could you check if the same SDK should be removed from the Universal App support?

The packages are:

- `Install-Package Expression.Blend.Sdk3` for blend sdk 3 (created by me waiting to be merged in the following one, I've already asked the owner of the other package)
- `Install-Package Expression.Blend.Sdk` for blend sdk 4 & 4.5

**Pull request merged**
