### PR TITLE
In some cases AsReadOnly returned the same instance

### PR DESCRIPTION
**Pull request by mauroservienti**
It is a design guideline that linq-like extension methods should always return a new list instance when operating on list following the monad/functional approach of immutable types.

@micdenny please review.

Version not yet bumped, I don't think it is needed there is another pending PR that already introduced a fix and bumped the version since we are going to release this 2 fixes at the same time should we bump the version twice?

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny could you please chime in and review?

**Comment by mauroservienti** [comment]
merged the huge tab/spaces PR from develop and bumped the version.

**Comment by micdenny** [comment]
this is good, merging

**Comment by mauroservienti** [comment]
cool

**Pull request merged**
