### PR TITLE
1.5.3-Release

### PR DESCRIPTION
**Pull request by mauroservienti**
Releasing to production 1.5.3, the #195 fix has been tested by the user confirming that the issue is resolved.
@micdenny up to you to release to NuGet for the first time :-)

### CODE REVIEW

**Comment by micdenny** [comment]
> @micdenny up to you to release to NuGet for the first time :-)

should I say thanks for this?! :stuck_out_tongue: 

merging and praying :pray:

**Comment by micdenny** [comment]
wait sorry.... this PR was requested against `develop` but shouldn't be against `master`?

**Comment by mauroservienti** [comment]
> wait sorry.... this PR was requested against  develop  but shouldn't be against  master ?

oh...crap...right...fixing...wait

**Comment by micdenny** [comment]
> oh...crap...right...fixing...wait

:smile: probably you will need to create a new PR

**Pull request closed without merging**
